projects:
  tetrismldev:
    schemaPath: src/graphql/schema.json
    includes:
      - graphqlapi
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: graphqlapi
        docsFilePath: .
